#!/usr/bin/env bash
# Displays "To infinity and beyond" every 2 seconds; on SIGTERM prints "I am invincible!!!"
trap 'echo "I am invincible!!!"' TERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
